### PR TITLE
US8.DeleteFileOrFolder.feature done

### PR DESCRIPTION
**Pull request by VeronikaKrasnokutska**
US8.DeleteFileOrFolder.feature done

Generated my snippets 
Copy paste the snippets into the our "Step_Definitions.java" class and implemented logic

### CODE REVIEW

**Review by BadamkhandB — APPROVED** [review]
All looks great

**Review by ZaierAouani — APPROVED** [review]
Great work!

**Review by msebbata — APPROVED** [review]
looks good to me

**Review by KarinaFrei — APPROVED** [review]
Great job!

**Review by nshportun — APPROVED** [review]
Cool Cool

**Comment by LaylaNait** [comment]
Awsome!

**Comment by ghost** [comment]
"I love it"! *Fatma

**Pull request closed without merging**
