### PR TITLE
Naz

### PR DESCRIPTION
**Pull request by nshportun**

### CODE REVIEW

**Review by ghost — APPROVED** [review]
I trust your judgement, sir!

**Review by ghost — CHANGES_REQUESTED** [review]
It would probably be better to start the feature and step_def files with user story number, followed by name, to have a nice structure at the end

**Review by LaylaNait — COMMENTED** [review]
great job Naz I see you did all of USs, i learn a lot from your code ,  this will not be the final version of the project.  I will just merge it now !! and the final version everyone should push only  the US assigned to him so we will not have duplicated steps

**Review by ZaierAouani — APPROVED** [review]
Great job!

**Review by BadamkhandB — COMMENTED** [review]
Well Done!!

**Pull request merged**
